# Usa una imagen base de Node.js
FROM node:16

# Crea el directorio de trabajo
WORKDIR /app

# Copia los archivos del proyecto
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia el resto del código
COPY . .

# Construye el proyecto TypeScript
RUN npm run build

# Expone el puerto en el que corre la aplicación
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["./infrastructure/docker/init_node.sh"]