import * as z from 'zod';

export const PaymentSchema = z.object({
  UTCTimeFormat: z.string(),
  additionalInfo: z.string(),
  attendant: z.string(),
  currencyCode: z.string(),
  datosComercio: z.object({
    MCC: z.string(),
    ciudadComercio: z.string(),
    clientAppOrg: z.string(),
    comunaComercio: z.string(),
    dv: z.string(),
    idComercio: z.string(),
    paisComercio: z.string(),
    rut: z.string(),
  }),
  datosPago: z.object({
    cuotas: z.number(),
    iva: z.number(),
    monto: z.number(),
    monto_s_prop: z.number(),
    neto: z.number(),
    propina: z.number(),
    tipoComprobante: z.string(),
    tipoCuota: z.string(),
    totalExento: z.number(),
    vuelto: z.number(),
  }),
  datosSucursal: z.object({
    comunaSucursal: z.string(),
    direccionSucursal: z.string(),
    idSucursal: z.string(),
    idSucursalOP: z.string(),
    nombreSucursal: z.string(),
    paisSucursal: z.string(),
    regionSucursal: z.string(),
  }),
  datosTarjeta: z.object({
    bin: z.string(),
    abreviatura: z.string(),
    marca: z.string(),
    cardEntryMode: z.string(),
    cardSeqNumb: z.string(),
    tipo: z.string(),
    conditionCode: z.string(),
    fourDigits: z.string(),
    invoiceData: z.string(),
  }),
  idAlianza: z.string(),
  idPago: z.string(),
  idTerminal: z.string(),
  infoAdicional: z.object({
    canal: z.string(),
    card_entry: z.string(),
    portador: z.string(),
    serial_number: z.string(),
    sim_id: z.string(),
    version_app: z.string(),
    bins: z.object({
      date_file: z.string(),
      date_update: z.string(),
      record_count: z.number(),
      version: z.number(),
    }),
    emv_aid: z.object({
      date_file: z.string(),
      date_update: z.string(),
      version: z.number(),
    }),
    emv_capk: z.object({
      date_file: z.string(),
      date_update: z.string(),
      version: z.number(),
    }),
    errors: z.object({
      date_file: z.string(),
      date_update: z.string(),
      version: z.number(),
    }),
    propinaActiva: z.boolean(),
  }),
  localDate: z.string(),
  localTime: z.string(),
  localTimeFormat: z.string(),
  millisecDate: z.string(),
  rrn: z.string(),
  secureFields: z.object({
    track2: z.string(),
    track2ksn: z.string(),
  }),
});
